//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phase
    {
        public Phase()
        {
            this.ServiceProviders = new HashSet<ServiceProvider>();
        }
    
        public int PhaseID { get; set; }
        public string Phase1 { get; set; }
    
        public virtual ICollection<ServiceProvider> ServiceProviders { get; set; }
    }
}
