//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceProvider
    {
        public ServiceProvider()
        {
            this.ServiceProviderIssues = new HashSet<ServiceProviderIssue>();
        }
    
        public int ServiceProviderID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> GoLiveDate { get; set; }
        public Nullable<int> ProjectManagerID { get; set; }
        public Nullable<int> PhaseID { get; set; }
        public Nullable<decimal> Fees { get; set; }
        public Nullable<int> TypeID { get; set; }
        public string Update { get; set; }
    
        public virtual Phase Phase { get; set; }
        public virtual ICollection<ServiceProviderIssue> ServiceProviderIssues { get; set; }
        public virtual Type Type { get; set; }
        public virtual Type Type1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
