

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataLayer
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class VendorAPIWebEntities : DbContext
{
    public VendorAPIWebEntities()
        : base("name=VendorAPIWebEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Phase> Phases { get; set; }

    public DbSet<ServiceProviderIssue> ServiceProviderIssues { get; set; }

    public DbSet<ServiceProvider> ServiceProviders { get; set; }

    public DbSet<Status> Status { get; set; }

    public DbSet<Type> Types { get; set; }

    public DbSet<User> Users { get; set; }

    public DbSet<UserRole> UserRoles { get; set; }

}

}

